### ISSUE TITLE
메인 화면 구현하기

### ISSUE THREAD

**Issue by choco-tyranno** [choco-tyranno/TictocCroc_MetroSearch#3]
최근 검색 목록이 표기되는 메인 화면을 구현합니다.

***

## Task List 
* UI
- [x] 메인 화면 스크린 구성 : Navigation component, Fragment
- [x] 메인 화면 Parent View : ConstaintLayout
- [x] 검색 뷰 : SearchView
- [x] 최근 검색 목록 : Chip
- [x] 전체 삭제 버튼 : MaterialButton
- [x] 검색 영역 '터치' 시 화면 이동
- [x] 검색 기록 표시(재실행 시 리스트 유지)
- [x] 검색 기록 아이템 가로로 나열. 넘칠 시 줄내림
- [x] 검색 기록 개별 삭제
- [x] 검색 기록 전체 삭제

* Data
- [x] data model : Station
